import 'package:flutter/material.dart';
import 'decoration_model.dart';

enum HairRenderType { hat, pin }

/// Server IDs follow the confirmed ascending Figma category order (2026-10-08).
/// Frames remove export canvas padding at render time; source PNGs stay intact.
class AccessoryRenderSpec {
  final String asset;
  final Size originalSize;
  final Size canvasSize;
  final Rect thumbnailBounds;
  final HairRenderType? hairType;
  final Rect? sourceFrame;
  const AccessoryRenderSpec(
    this.asset,
    this.originalSize, {
    required this.canvasSize,
    required this.thumbnailBounds,
    this.hairType,
    this.sourceFrame,
  });
}

const accessoryRenderCatalog = <int, AccessoryRenderSpec>{
  13: AccessoryRenderSpec(
    'assets/accessories/crown.png',
    Size(110, 80),
    canvasSize: Size(110, 80),
    thumbnailBounds: Rect.fromLTWH(26, 19, 61, 44),
    hairType: HairRenderType.hat,
  ),
  3: AccessoryRenderSpec(
    'assets/accessories/beanie_yellow.png',
    Size(110, 80),
    canvasSize: Size(110, 80),
    thumbnailBounds: Rect.fromLTWH(9, 8, 94, 67),
    hairType: HairRenderType.hat,
  ),
  2: AccessoryRenderSpec(
    'assets/accessories/beanie_green.png',
    Size(110, 80),
    canvasSize: Size(110, 80),
    thumbnailBounds: Rect.fromLTWH(8, 4, 94, 68),
    hairType: HairRenderType.hat,
  ),
  1: AccessoryRenderSpec(
    'assets/accessories/beanie_brown.png',
    Size(110, 80),
    canvasSize: Size(110, 80),
    thumbnailBounds: Rect.fromLTWH(7, 8, 94, 66),
    hairType: HairRenderType.hat,
  ),
  9: AccessoryRenderSpec(
    'assets/accessories/bow_red.png',
    Size(60, 60),
    canvasSize: Size(60, 60),
    thumbnailBounds: Rect.fromLTWH(0, 18, 59, 31),
    hairType: HairRenderType.pin,
  ),
  10: AccessoryRenderSpec(
    'assets/accessories/bow_mint.png',
    Size(60, 60),
    canvasSize: Size(60, 60),
    thumbnailBounds: Rect.fromLTWH(0, 18, 60, 31),
    hairType: HairRenderType.pin,
  ),
  11: AccessoryRenderSpec(
    'assets/accessories/bow_yellow.png',
    Size(60, 60),
    canvasSize: Size(60, 60),
    thumbnailBounds: Rect.fromLTWH(0, 18, 59, 30),
    hairType: HairRenderType.pin,
  ),
  7: AccessoryRenderSpec(
    'assets/accessories/pin_white.png',
    Size(60, 60),
    canvasSize: Size(60, 60),
    thumbnailBounds: Rect.fromLTWH(9, 18, 40, 26),
    hairType: HairRenderType.pin,
  ),
  6: AccessoryRenderSpec(
    'assets/accessories/pin_red.png',
    Size(60, 60),
    canvasSize: Size(60, 60),
    thumbnailBounds: Rect.fromLTWH(8, 18, 39, 26),
    hairType: HairRenderType.pin,
  ),
  5: AccessoryRenderSpec(
    'assets/accessories/pin_yellow.png',
    Size(60, 60),
    canvasSize: Size(60, 60),
    thumbnailBounds: Rect.fromLTWH(10, 18, 40, 26),
    hairType: HairRenderType.pin,
  ),
  8: AccessoryRenderSpec(
    'assets/accessories/pin_blue.png',
    Size(60, 60),
    canvasSize: Size(60, 60),
    thumbnailBounds: Rect.fromLTWH(10, 16, 40, 26),
    hairType: HairRenderType.pin,
  ),
  12: AccessoryRenderSpec(
    'assets/accessories/pin_heart.png',
    Size(60, 60),
    canvasSize: Size(60, 60),
    thumbnailBounds: Rect.fromLTWH(10, 11, 41, 36),
    hairType: HairRenderType.pin,
  ),
  4: AccessoryRenderSpec(
    'assets/accessories/hat_yellow.png',
    Size(110, 80),
    canvasSize: Size(110, 80),
    thumbnailBounds: Rect.fromLTWH(11, 16, 87, 59),
    hairType: HairRenderType.hat,
  ),
  20: AccessoryRenderSpec(
    'assets/accessories/raincoat_yellow.png',
    Size(200, 230),
    canvasSize: Size(200, 230),
    thumbnailBounds: Rect.fromLTWH(6, 9, 185, 211),
  ),
  14: AccessoryRenderSpec(
    'assets/accessories/cape_birthday.png',
    Size(140, 100),
    canvasSize: Size(354, 354),
    thumbnailBounds: Rect.fromLTWH(94, 202, 105, 71),
    sourceFrame: Rect.fromLTWH(71, 176, 140, 100),
  ),
  17: AccessoryRenderSpec(
    'assets/accessories/cape_mint.png',
    Size(140, 100),
    canvasSize: Size(140, 100),
    thumbnailBounds: Rect.fromLTWH(23, 26, 97, 70),
  ),
  16: AccessoryRenderSpec(
    'assets/accessories/collar_bell.png',
    Size(140, 100),
    canvasSize: Size(140, 100),
    thumbnailBounds: Rect.fromLTWH(27, 37, 92, 48),
  ),
  15: AccessoryRenderSpec(
    'assets/accessories/tie.png',
    Size(140, 100),
    canvasSize: Size(140, 100),
    thumbnailBounds: Rect.fromLTWH(16, 13, 104, 72),
  ),
  19: AccessoryRenderSpec(
    'assets/accessories/clothes_beige.png',
    Size(227, 230),
    canvasSize: Size(353, 337),
    thumbnailBounds: Rect.fromLTWH(83, 138, 225, 157),
    sourceFrame: Rect.fromLTWH(70, 65, 227, 230),
  ),
  18: AccessoryRenderSpec(
    'assets/accessories/clothes_green.png',
    Size(210, 230),
    canvasSize: Size(210, 230),
    thumbnailBounds: Rect.fromLTWH(12, 72, 190, 156),
  ),
  21: AccessoryRenderSpec(
    'assets/accessories/shoes_black.png',
    Size(110, 60),
    canvasSize: Size(398, 354),
    thumbnailBounds: Rect.fromLTWH(97, 309, 91, 31),
    sourceFrame: Rect.fromLTWH(97, 290.364, 91, 49.636),
  ),
  22: AccessoryRenderSpec(
    'assets/accessories/shoes_red.png',
    Size(110, 60),
    canvasSize: Size(403, 353),
    thumbnailBounds: Rect.fromLTWH(138, 302, 101, 41),
    sourceFrame: Rect.fromLTWH(138, 287.909, 101, 55.091),
  ),
  23: AccessoryRenderSpec(
    'assets/accessories/shoes_blue.png',
    Size(110, 60),
    canvasSize: Size(381, 353),
    thumbnailBounds: Rect.fromLTWH(126, 286, 116, 60),
    sourceFrame: Rect.fromLTWH(126, 282.727, 116, 63.273),
  ),
};

final previewAccessories = <AccessoryItem>[
  AccessoryItem(
    ownershipId: null,
    accessoryId: 1,
    name: '갈색 비니',
    image: accessoryRenderCatalog[1]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 2,
    name: '초록 비니',
    image: accessoryRenderCatalog[2]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 3,
    name: '노란 비니',
    image: accessoryRenderCatalog[3]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 4,
    name: '노란 모자',
    image: accessoryRenderCatalog[4]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 5,
    name: '노란 핀',
    image: accessoryRenderCatalog[5]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 6,
    name: '빨간 핀',
    image: accessoryRenderCatalog[6]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 7,
    name: '흰 핀',
    image: accessoryRenderCatalog[7]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 8,
    name: '파란 핀',
    image: accessoryRenderCatalog[8]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 9,
    name: '빨간 리본',
    image: accessoryRenderCatalog[9]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 10,
    name: '민트 리본',
    image: accessoryRenderCatalog[10]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 11,
    name: '노란 리본',
    image: accessoryRenderCatalog[11]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 12,
    name: '하트 핀',
    image: accessoryRenderCatalog[12]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 13,
    name: '왕관',
    image: accessoryRenderCatalog[13]!.asset,
    category: AccessoryCategory.hair,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 14,
    name: '생일 케이프',
    image: accessoryRenderCatalog[14]!.asset,
    category: AccessoryCategory.cape,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 15,
    name: '넥타이',
    image: accessoryRenderCatalog[15]!.asset,
    category: AccessoryCategory.cape,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 16,
    name: '방울 목줄',
    image: accessoryRenderCatalog[16]!.asset,
    category: AccessoryCategory.cape,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 17,
    name: '민트 케이프',
    image: accessoryRenderCatalog[17]!.asset,
    category: AccessoryCategory.cape,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 18,
    name: '초록 옷',
    image: accessoryRenderCatalog[18]!.asset,
    category: AccessoryCategory.clothes,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 19,
    name: '베이지 옷',
    image: accessoryRenderCatalog[19]!.asset,
    category: AccessoryCategory.clothes,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 20,
    name: '노란 우비',
    image: accessoryRenderCatalog[20]!.asset,
    category: AccessoryCategory.clothes,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 21,
    name: '검정 신발',
    image: accessoryRenderCatalog[21]!.asset,
    category: AccessoryCategory.shoes,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 22,
    name: '빨간 신발',
    image: accessoryRenderCatalog[22]!.asset,
    category: AccessoryCategory.shoes,
    isOwned: true,
    isEquipped: false,
  ),
  AccessoryItem(
    ownershipId: null,
    accessoryId: 23,
    name: '파란 신발',
    image: accessoryRenderCatalog[23]!.asset,
    category: AccessoryCategory.shoes,
    isOwned: true,
    isEquipped: false,
  ),
];
